name: Study BLoG
title: Home | Study BLoG
description: 코딩 공부와 취미생활을 하는 나만의 블로그 입니다.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Programing
    url: /contact
  - title: Hobby
    url: /feed.xml
email: dlgusrb1596@naver.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
